### ISSUE TITLE
Can we change the font size of the axis?

### ISSUE THREAD

**Issue by epioneMW** [hrbrmstr/streamgraph#32]

**Comment by olyerickson** [comment]
I'm also looking for guidance on this. I looked in e.g. sg_axis_x() source and it wasn't clear...

This is an *awesome* package, thanks!

**Comment by olyerickson** [comment]
Note, a blogger had this same problem, noted here:
https://ouzor.github.io/blog/2015/08/31/twitter-streamgraph.html

**Comment by elfatherbrown** [comment]
Use css for this. Like so:

```css
svg text {
  font-family: inherit;
  fill: lightgray;
  font-size: 1.1em;
}
```

there are also speciffic selectors for each axis. Inspect the axis text element to find out. It as something like: x.axis text { etc.. }
